sudo: false
cache: bundler
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2

branches:
  only:
    - master

notifications:
  slack:
    secure: wZ1UPEcH/Zf/wSPvpR1q76vpUQvAEGuwR5500ML8C+shW7PedvuSZaiZYAOZxhyD17RXzXYroON0ArEk3NUcKD8supPzYjUWzCeWDIFaYxEb7dOm7tpRBf4GuQ/oy8HGsBi947ZTX3WytGWZU0q0aRu2EirPcoY05vzley/hYTI=
