sudo: false
cache: bundler
language: ruby
rvm:
  - 2.3.0
  - 2.1.8
  - 2.2.4
  - ruby-head
  - 2.0
  - 1.9
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.0
    - rvm: 1.9
  fast_finish: true
notifications:
  slack:
    secure: nGQv46FQ3FlYh9wKnshCucxN4MqQVPwflNunrICiHqfo0+6lHPijZY783BILolnKJuFIXccgjZrQ/tQjKBwaLEXEHMWWIUgq0xuO7GpQiamgdrar7Ohdv5nbVl5el/YJk2ok1tPEmIHGtgLqDPvGEDbDiR2x0N5gy6Po836NzOY=
